service: layers

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

layers:
  helpers:
    path: helpers

resources:
   Outputs:
     HelpersLayerExport:
       Value:
         Ref: HelpersLambdaLayer
       Export:
         Name: HelpersLambdaLayer