service: todos

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-offline

functions:
  hello:
    handler: src/handler.main
    events:
      - http:
          path: hello
          method: get
          cors: true
    layers:
      - ${cf:layers-${self:provider.stage}.LoggingLayerExport}